// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs
// https://dbdiagram.io/

Table usuario.persona {
  id integer [primary key, increment]
  nombre varchar(30) [not null]
  apellido_pat varchar(22) [not null]
  apellido_mat varchar(22)
}

Table usuario.tipo {
  id integer [primary key, increment]
  nombre varchar(30) [not null]

  Note: 'Tipo de usuario: maestro, admin, alumno, etc.'
}

Table usuario.acceso {
  persona integer [ref: > usuario.persona.id]
  google_id varchar(30) [null]
  email varchar(50) [not null]
  password varchar(50) [not null]
  tipo integer [ref: > usuario.tipo.id]
  indexes {
	email [name: 'email_index']
  }
}

Table usuario.datos {
  persona integer [ref: - usuario.persona.id]
  email2 varchar [null]
  telefono char(15)
  celular char(15)
}
