// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs
// https://dbdiagram.io/

Table usuario.persona [headercolor: #CCCCFF] {
  id integer [primary key, increment]
  nombre varchar(30) [not null]
  apellido_pat varchar(22) [not null]
  apellido_mat varchar(22)
}

Table usuario.tipo [headercolor: #CCCCFF] {
  id integer [primary key, increment]
  descripcion varchar(30) [not null]

  Note: 'Tipo de usuario: maestro, admin, alumno, etc.'
}

Table usuario.acceso [headercolor: #CCCCFF] {
  persona_id integer [ref: > usuario.persona.id]
  google_id varchar(30) [null]
  email varchar(50) [not null]
  tipo integer [ref: > usuario.tipo.id]
  habilitado bool [not null]
  indexes {
	email [name: 'email_index']
  }
}
table usuario.artnoc [headercolor: #CCCCFF]{
  persona_id integer [ref: > usuario.persona.id]
  algundato varchar(64) [not null]
}

Table usuario.datos [headercolor: #CCCCFF] {
  persona_id integer [ref: - usuario.persona.id]
  email2 varchar [null]
  telefono char(15)
  celular char(15)
  calle char(20)
  num_ext char(20)
  num_int char(20)
}

Table escolar.asignatura [headercolor: #FFCCCC] {
  id integer [primary key, increment]
  creditos integer [not null]
  horas_clase integer [not null]
  horas_practicas integer [not null]
  clave char(20) [not null]
  nombre varchar(30) [not null]
}

Table escolar.carrera [headercolor: #FFCCCC] {
  id integer [primary key, increment]
  creditos integer [not null]
  clave char(16) [not null]
  nombre varchar(30) [not null]
}

Table escolar.ciclo [headercolor: #FFCCCC] {
  id integer [primary key, increment]
  inicio date [not null]
  fin date [not null]
  nombre varchar(30) [not null]
}
Table escolar.asignatura_carrera [headercolor: #FFCCCC] {
  id integer [primary key, increment]
  asignatura_id integer [ref: >escolar.asignatura.id] 
  carrera_id integer [ref: >escolar.carrera.id]
}

Table escolar.grupo {
  id integer [primary key, increment]
  docente_id integer [ref: >usuario.persona.id]
  asignatura_carrera_id integer [ref: >escolar.asignatura_carrera.id]
  ciclo_id integer [ref: >escolar.ciclo.id]
  identificador varchar(5) [not null]
} 
Table escolar.alumnos{
  alumno_id integer [ref: >usuario.persona.id]
  grupo_id integer [ref: >escolar.grupo.id]
}

Table escolar.asistencia{
  fecha date [not null]
  alumno_id integer [ref: >usuario.persona.id]
  grupo_id integer [ref: >escolar.grupo.id]
  indexes {
	  fecha [name: 'fecha_index']
  }
}
